# Change these first
owner: kslow2168 # Your GitHub organization or username, where this repository lives
repo: AntzMonitor # The name of this repository

sites:
  - name: Maxis WMS
    url: https://maxis.antz.app
  - name: ANTZ DEMO
    url: https://demo.antz.app
  - name: DOGGO WEB
    url: https://smartesg.doggo.my
  - name: DOGGO Smart ESG
    url: https://smartesgapp.doggo.my
  - name: IPv6 test
    url: dahsboard.inchz.io
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://kslow2168.github.io/AntzMonitor
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ANTZ Monitor
  introTitle: "Monitor ANTZ and DOGGO instances"
  introMessage: NONE
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
